# Etapa de Nginx (servidor web)
FROM nginx:alpine

# Copiar tu aplicación al contenedor
COPY . /usr/share/nginx/html

# Copiar el archivo de configuración de Nginx
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80
EXPOSE 80

# Comando por defecto
CMD ["nginx", "-g", "daemon off;"]
